In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


For the next cell, make sure you've downloaded the proper zip file (look at Discord) and put it in your Google Drive. Remeber that once your drive is mounted you can right click the files and folders on the left of the screen to find their* paths*.

You may need to change the path inside the read_csv function below to a different path.

In [ ]:
# import Pandas library and convert csv file to pandas dataframe
import pandas as pd

#CHANGE THE PATH HERE IF NEEDED
df = pd.read_csv('/content/gdrive/MyDrive/Supreme Court Database/SCDB_2022_01_justiceCentered_Citation.csv.zip', encoding='iso-8859-1')

<ipython-input-2-6faff3ed820e>:5: DtypeWarning: Columns (6,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/gdrive/MyDrive/Supreme Court Database/SCDB_2022_01_justiceCentered_Citation.csv.zip', encoding='iso-8859-1')


In [ ]:
# import Pandas library and convert csv file to pandas dataframe
import pandas as pd

#CHANGE THE PATH HERE IF NEEDED
df = pd.read_csv('/content/gdrive/MyDrive/SCDB_2022_01_justiceCentered_Citation.csv', encoding='iso-8859-1')

<ipython-input-2-9b02ee4dfe75>:5: DtypeWarning: Columns (6,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/gdrive/MyDrive/SCDB_2022_01_justiceCentered_Citation.csv', encoding='iso-8859-1')


In [ ]:
# Find the names of justices
df['justiceName'].unique()

array(['HHBurton', 'RHJackson', 'WODouglas', 'FFrankfurter', 'SFReed',
       'HLBlack', 'WBRutledge', 'FMurphy', 'FMVinson', 'TCClark',
       'SMinton', 'EWarren', 'JHarlan2', 'WJBrennan', 'CEWhittaker',
       'PStewart', 'BRWhite', 'AJGoldberg', 'AFortas', 'TMarshall',
       'WEBurger', 'HABlackmun', 'LFPowell', 'WHRehnquist', 'JPStevens',
       'SDOConnor', 'AScalia', 'AMKennedy', 'DHSouter', 'CThomas',
       'RBGinsburg', 'SGBreyer', 'JGRoberts', 'SAAlito', 'SSotomayor',
       'EKagan', 'NMGorsuch', 'BMKavanaugh', 'ACBarrett'], dtype=object)

In [ ]:
# Create a new dataframe from the origional dataframe called df_Roberts, where all entries are of justice Roberts
df_Roberts = df[(df['justiceName'] == 'JGRoberts')]

In [ ]:
# Look at the direction column in our new Roberts dataframe
df_Roberts['direction']

In [ ]:
# Try and get the sum of the values in this column but using the sum() function
# NOTE: This cell will NOT work properly! That's okay.
sum(df_Roberts['direction'])


nan

In [ ]:
# Why didn't it give us a number? Let's check to see the different unique values in the direction column of our dataframe:
df_Roberts['direction'].unique()

array([ 2.,  1., nan])

In [ ]:
# Our sum function didn't work because of the nan values inside the column. So, we want to get rid of those.

# Here we will reassign our Roberts dataframe to only contain rows where the direction column's value is greater than zero.
df_Roberts = df_Roberts[df_Roberts['direction'] > 0]

In [ ]:
# Check to see if nan values are gone
df_Roberts['direction'].unique()

array([2., 1.])

In [ ]:
# Get sum of the column
roberts_sum = sum(df_Roberts['direction'])

In [ ]:
# Average Roberts' sum by dividing it by the length of entries in the column

score = roberts_sum / len(df_Roberts['direction'])

In [ ]:
# What does this number represent? Can you think of other ways, using the csv, to measure something like this?
score

1.4152473641524737

In [ ]:
df_case = df[(df['caseId'] == '2021-069')]
df_case

In [ ]:
df_case["decisionDirection"][82009]

2.0

In [ ]:
prediction = 1.0
is_correct=2.0
actual = df_case["decisionDirection"][82009]

In [ ]:
if(prediction == actual): 
  is_correct= True
else:
  is_correct = False
is_correct

False

In [ ]:
def is_correct(prediction, actual):
  
  if(prediction == actual):
    prediction = True
    return prediction
  else:
    prediction = False
    return prediction

  return is_correct

In [ ]:
is_correct ("pizza", "apple")

False

It Works Now

In [ ]:
df_Barret = df[(df['justiceName']=='ACBarrett')]
df_Barret

In [ ]:
def is_correct(decisionDirection, actual=2.0):
    if(decisionDirection == actual):
      prediction = True
    else:
      prediction = False
    return prediction


In [ ]:
def base_model_score(df_len, true_sum):
  return true_sum / df_len

In [ ]:
def data_Barret():
  true_sum = 0
  df_Barret = df[(df['justiceName']=='ACBarrett')]
  for x in range(len( df_Barret)):
    df_Barret = df_Barret[df_Barret['decisionDirection'] != "nan"]
  
    decisionDirection = df_Barret['decisionDirection'].iloc[x-1]
    prediction = is_correct(decisionDirection, 2)
  
    # print (f"Decision Direction: {actual}, Actual: {decisionDirection}, Prediction: {prediction}")

    if prediction:
      true_sum += 1

  score_1 = base_model_score(len(df_Barret), true_sum)

  print (f"True Sum: {true_sum}")
  print (f"Score: {score_1}")

In [ ]:
data_Barret()

True Sum: 47
Score: 0.36153846153846153


Work on finding average scores of Supreme court in general

In [ ]:
judges = ['HHBurton', 'RHJackson', 'WODouglas', 'FFrankfurter', 'SFReed',
       'HLBlack', 'WBRutledge', 'FMurphy', 'FMVinson', 'TCClark',
       'SMinton', 'EWarren', 'JHarlan2', 'WJBrennan', 'CEWhittaker',
       'PStewart', 'BRWhite', 'AJGoldberg', 'AFortas', 'TMarshall',
       'WEBurger', 'HABlackmun', 'LFPowell', 'WHRehnquist', 'JPStevens',
       'SDOConnor', 'AScalia', 'AMKennedy', 'DHSouter', 'CThomas',
       'RBGinsburg', 'SGBreyer', 'JGRoberts', 'SAAlito', 'SSotomayor',
       'EKagan', 'NMGorsuch', 'BMKavanaugh', 'ACBarrett']

score_list = []

for i in range(len(judges)):
  df_ingeneral = df[(df['justiceName'] == judges[i])]
  df_ingeneral = df_ingeneral[df_ingeneral['decisionDirection'] > 0]
  total_sum = sum(df_ingeneral['decisionDirection'])
  score = total_sum / len(df_ingeneral['decisionDirection'])
  print(judges[i])
  print(score)
  score_list.append(score)

score_2 = sum(score_list) /  len(score_list)
print(f"Average Score: {score_2}")

In [ ]:
import random
print(f"Random Score: {1+random.random()}")
print(f"Average Score: {score_2}")
# random.choice(judges)

Random Score: 1.4717161532463923
Average Score: 1.5480324039529338


In [ ]:
judges = ['ACBarrett', 'RHJackson',  'JGRoberts', 'CThomas', 'SAAlito', 'SSotomayor', 'EKagan', 'NMGorsuch', 'BMKavanaugh']

score_list = []


df_ingeneral = df[(df['justiceName'] == 'ACBarrett')]
df_ingeneral = df_ingeneral[df_ingeneral['decisionDirection'] > 0]
total_sum = sum(df_ingeneral['decisionDirection'])
score = total_sum / len(df_ingeneral['decisionDirection'])
print(judges[i])
print(score)
score_list.append(score)



print(df_ingeneral)

In [ ]:
df_Barret

Prediction Model

In [ ]:
def validation(predict_party, judge_name, case_Number):
  right = 0
  wrong = 0
  if predict_party == 2.0:
    predicted_vote = 'Liberal'
  if predict_party == 1.0:
    predicted_vote = 'Conservative'

  df_caseId = df[(df['caseId'] == case_Number)]
  df_caseId = df_caseId[(df_caseId['direction']) > 0 ]

  judge_data = df_caseId[df_caseId['justiceName']==judge_name]
  for index, row in df_caseId.iterrows():
    if row['justiceName'] != judge_name:
      continue

    if row['direction'] == 2.0:
      actual_vote = 'Liberal'
    if row['direction'] == 1.0:
      actual_vote = 'Conservative'

    if row['direction'] == predict_party:
      print(f"Prediction is correct for judge: {judge_name}, case id: {row['caseId']}, Predicted vote: {predicted_vote}, Actual vote: {actual_vote}")
      right =+ 1
    else:
      print(f"Prediction is incorrect for judge: {judge_name}, case id: {row['caseId']}, Predicted vote: {predicted_vote}, Actual vote: {actual_vote}")
      wrong =+1
  return right, wrong

  # if right > wrong:
  #   print("Court Decision's Actual Decision on Average is Liberal")
  # else:
  #   print("Court Decision's Actual Decision on Average is Conservative")

 

In [ ]:
def prediction_model():
  liberal = 0
  conservative = 0
  judges = ['HHBurton', 'RHJackson', 'WODouglas', 'FFrankfurter', 'SFReed',
       'HLBlack', 'WBRutledge', 'FMurphy', 'FMVinson', 'TCClark',
       'SMinton', 'EWarren', 'JHarlan2', 'WJBrennan', 'CEWhittaker',
       'PStewart', 'BRWhite', 'AJGoldberg', 'AFortas', 'TMarshall',
       'WEBurger', 'HABlackmun', 'LFPowell', 'WHRehnquist', 'JPStevens',
       'SDOConnor', 'AScalia', 'AMKennedy', 'DHSouter', 'CThomas',
       'RBGinsburg', 'SGBreyer', 'JGRoberts', 'SAAlito', 'SSotomayor',
       'EKagan', 'NMGorsuch', 'BMKavanaugh', 'ACBarrett']
  score_list = []
  court_decision = 0
  for i in range(len(judges)):
    party = 0.0
    df_ingeneral = df[(df['justiceName'] == judges[i])]
    df_ingeneral = df_ingeneral[df_ingeneral['decisionDirection'] > 0]
    total_sum = sum(df_ingeneral['decisionDirection'])
    score = total_sum / len(df_ingeneral['decisionDirection'])
    
    import random
    randomScore = 1+random.random()
    print(judges[i])
    print(f"Average Score: {score}")
    print(f"Random Score: {randomScore}")

    if score > randomScore:
      print("Guess: Liberal")
      liberal =+ 1
      party = 2.0
    else:
      print("Guess: Conservative")
      conservative =+ 1
      party = 1.0
    score_list.append(score)

    #validation(party,judges[i], '2020-006')

  if liberal > conservative:
    print("Court  Decision's Predicted Decision on Average is Liberal")
    court_decision = 2
  else:
    print("Court Decision's Predicted Decision on Average is Conservative")
    court_decision = 1
  return court_decision

In [ ]:
df_Barret = df[(df['justiceName']=='ACBarrett')]
right = 0 
wrong = 0
df_Barret_reset = df_Barret.reset_index()
for i in range(len(df_Barret)):
  
  if prediction_model() == df_Barret_reset['decisionDirection'][i]:
    right = right + 1
    accuracy = right/ len(df_Barret)
  if right >= wrong:
   print("Court Decision's Actual Decision on Average is Liberal")
  else:
   print("Court Decision's Actual Decision on Average is Conservative") 
   
print(f"Accuracy percentage: {accuracy}")


    # score_3 = sum(score_list) /  len(score_list)
    # import random
    # print(f"Average Score of the Court as a whole: {score_3}")
    # df_caseId


IMPORTANT VARIABLES I FOUND

Majority and Minority Voting by Justice: 1	dissent, 2	majority

Split Vote: 1	first vote on issue/legal provision, 2	second vote on issue/legal provision

Formal Alteration of Precedent: 0	no determinable alteration of precedent, 
1	precedent altered

Unusual Disposition: 0	no unusual disposition specified, 1	unusual disposition

Decision Direction Dissent: 0	dissent in opposite direction, 1	majority and dissent in same direction

Issue Area: 1	Criminal Procedure,
2	Civil Rights,
3	First Amendment,
4	Due Process,
5	Privacy,
6	Attorneys,
7	Unions,
8	Economic Activity,
9	Judicial Power,
10	Federalism,
11	Interstate Relations,
12	Federal Taxation,
13	Miscellaneous,
14	Private Action

ORAL ARGUMENTS: https://www.supremecourt.gov/oral_arguments/argument_audio/2022

In [ ]:
df_new = df[['caseId','justiceName','petitioner', 'respondent', 'caseSource', 'caseOrigin', 'issue', 'issueArea','decisionDirection']]
df_new

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

df_filtered = df.dropna(subset=['issueArea', 'direction'])

X = df_filtered['issueArea'].values.reshape(-1, 1)
y = df_filtered['direction']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create an MLPClassifier
mlp = MLPClassifier(random_state=42)

# Train the classifier on the input data
mlp.fit(X_train, y_train)

# Get predictions on the test data
y_pred = mlp.predict(X_test)

# Compute the confusion matrix and accuracy
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

# Print the confusion matrix and accuracy
print(cm)
print(accuracy)

[[4789 6229]
 [3820 8360]]
0.5668161048366238


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:693: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


New Prediction Model

In [ ]:
from pandas.core.arrays import categorical
categorical = ['justice','petitioner', 'respondent', 'caseSource', 'caseOrigin', 'issue', 'issueArea']

In [ ]:
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder
X_categorical = OneHotEncoder().fit_transform(df_filtered[categorical].values).toarray()
#X = input area 

X_categorical[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

df_filtered = df.dropna(subset=['justice','petitioner', 'respondent', 'caseSource', 'caseOrigin', 'issue', 'issueArea','direction'])

X = df_filtered[['justice','petitioner', 'respondent', 'caseSource', 'caseOrigin', 'issue', 'issueArea']].values
y = df_filtered['direction']

X_train, X_test, y_train, y_test = train_test_split(X_categorical, y, test_size=0.3, random_state=42)


# Create an MLPClassifier
mlp = MLPClassifier(random_state=42)

# Train the classifier on the input data
mlp.fit(X_train, y_train)

# Get predictions on the test data
y_pred = mlp.predict(X_test)

# Compute the confusion matrix and accuracy
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

# Print the confusion matrix and accuracy
print(cm)
print(accuracy)

Assignment:

Download the oral arguments and convert that to text.

How to make a document into something that the computer can learn.



In [ ]:
#Use this for the assignment
sentence = "This is a sentence"
end= sentence.split("is")[2]

In [ ]:
end

' a sentence'

In [ ]:
df = pd.DataFrame(columns = ['words'])

In [ ]:
pip install PyPDF2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 11.0 MB/s eta 0:00:00


In [ ]:
import requests

url = "https://www.supremecourt.gov/oral_arguments/argument_transcripts/2020/20-543_hgci.pdf"

response = requests.get(url)

with open("20-543_hgci.pdf", "wb") as file:
    file.write(response.content)

In [ ]:
import PyPDF2

# Open the PDF file in read-binary mode
with open('20-543_hgci.pdf', 'rb') as file:

    # Create a PDF reader object
    reader = PyPDF2.PdfReader(file)

    # Get the total number of pages in the PDF file
    num_pages = len(reader.pages)

    # Extract text from each page
    text = ''
    for page in reader.pages:
        text += page.extract_text()

print(text)

In [ ]:
text_split = text.strip().replace('\n','').split("ROBERTS:")
len(text_split)

47

In [ ]:
stop_words = ['MR.','MS',':']
strings = []
for stop_word in stop_words:
  strings.append(text_split[2].split(stop_word)[0])
if len(strings[0]) > len(strings[1]):
  print(strings[1])
else:
  print(strings[0])
  

  Counsel, as I think you confirmed in this opening statement, you rely heavily on the legislative history, the congressional purpose, the post- enactment history, and there was a time when this Court also relied on those sources, but this -- this is not that time. And what is the best case you can cite from recent years for your -- your general approach? 


Create a subset of modern court (Barret Subset data)

Two columns: 1st Colums Words, wnd Column Word embbedings

Every oral argument for every case in that dataframe 

Make a list for every justice 

Takeing those columns into embbed words

In [ ]:
import requests
from bs4 import BeautifulSoup
import os
from urllib.parse import urljoin

In [ ]:
pdf_links = ["https://www.supremecourt.gov/oral_arguments/argument_transcripts/2009/08-1371.pdf", "https://www.supremecourt.gov/oral_arguments/argument_transcripts/2009/08-1332.pdf", "https://www.supremecourt.gov/oral_arguments/argument_transcripts/2009/09-367.pdf", "https://www.supremecourt.gov/oral_arguments/argument_transcripts/2009/09-337.pdf", "https://www.supremecourt.gov/oral_arguments/argument_transcripts/2009/09-497.pdf", "https://www.supremecourt.gov/oral_arguments/argument_transcripts/2009/09-448.pdf", "https://www.supremecourt.gov/oral_arguments/argument_transcripts/2009/09-475.pdf", "https://www.supremecourt.gov/oral_arguments/argument_transcripts/2009/09-559.pdf"]
for link in soup.find_all("a"):
    href = link.get("href")
    if href and href.endswith(".pdf"):
        absolute_url = urljoin(base_url, href)
        pdf_links.append(absolute_url)
        filename = os.path.basename(absolute_url)
        file_path = os.path.join("/content/gdrive/MyDrive/Supreme Court Database", filename)
        print(f"Downloading: {filename}")
        response = requests.get(absolute_url)
        with open(file_path, "wb") as file:
            file.write(response.content)

In [ ]:
print("Downloads completed.")
len(pdf_links)

Downloads completed.


8

Text Split Model

In [ ]:
import requests

url = "https://www.supremecourt.gov/oral_arguments/argument_transcripts/2020/20-543_hgci.pdf"

response = requests.get(url)

with open("20-543_hgci.pdf", "wb") as file:
    file.write(response.content)

In [ ]:
text_split = text.strip().replace('\n','').split("ROBERTS:")

In [ ]:
stop_words = ['MR.','MS',':']
strings = []
for stop_word in stop_words:
  strings.append(text_split[2].split(stop_word)[0])
if len(strings[0]) > len(strings[1]):
  print(strings[1])
else:
  print(strings[0])

  Counsel, as I think you confirmed in this opening statement, you rely heavily on the legislative history, the congressional purpose, the post- enactment history, and there was a time when this Court also relied on those sources, but this -- this is not that time. And what is the best case you can cite from recent years for your -- your general approach? 


In [ ]:
import gensim

In [ ]:
pip install gensim

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
word_vectors = gensim.models.KeyedVectors.load_word2vec_format('/content/gdrive/MyDrive/Supreme Court DatabaseND00-00429.rtf', binary=True)

text = '/content/gdrive/MyDrive/Supreme Court DatabaseND00-00429.rtf'
words = text.split()
vectors = []
for word in words:
    try:
       vector = word_vectors[word]
       vectors.append(vector)
    except KeyError:
        pass
if vectors:
    issue_embedding = np.mean(vectors, axis=0)
    print(issue_embedding)
else:
     print(np.zeros(100))

In [ ]:
value = '/content/gdrive/MyDrive/Supreme Court DatabaseND99-01145.rtf'  # Example value containing RTF formatting codes

# Remove RTF formatting codes using a regular expression
import re
value = re.sub(r'{\\.*?}', '', value)

# Convert the cleaned value to an integer
try:
    int_value = int(value)
except ValueError:
    # Handle the case where the cleaned value cannot be converted to an integer
    print("Error: The value is not a valid integer.")


Error: The value is not a valid integer.


In [ ]:
word_vectors = gensim.models.KeyedVectors.load_word2vec_format('/content/gdrive/MyDrive/Supreme Court DatabaseND99-01145.rtf', binary=True)
data = df

embeddings = []
for index, row in data.iterrows():
    text = row['Issues']
    words = text.split()
    vectors = []
    for word in words:
        try:
            vector = word_vectors[word]
            vectors.append(vector)
        except KeyError:
            pass
    if vectors:
        issue_embedding = np.mean(vectors, axis=0)
        embeddings.append(issue_embedding)

    else:
        embeddings.append(np.zeros(100))
df['Issue_Embeddings'] = embeddings

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import OneHotEncoder

cm = confusion_matrix(y_test, y_pred)

In [ ]:
df['direction'].fillna(-1).unique()

array([ 1.,  2., -1.])

In [ ]:
print(X_train.shape)
print(y_train.shape)

(54127, 1)
(54127,)


In [ ]:
df_caseId = df[(df['caseId'] == '2020-006')]
subset = df_caseId[['caseId', 'decisionDirection', 'justiceName', 'direction']]
subset

caseId  decisionDirection  justiceName  direction
80890  2020-006                2.0    JGRoberts        2.0
80891  2020-006                2.0      CThomas        1.0
80892  2020-006                2.0     SGBreyer        2.0
80893  2020-006                2.0      SAAlito        1.0
80894  2020-006                2.0   SSotomayor        2.0
80895  2020-006                2.0       EKagan        2.0
80896  2020-006                2.0    NMGorsuch        2.0
80897  2020-006                2.0  BMKavanaugh        2.0
80898  2020-006                2.0    ACBarrett        NaN

In [ ]:
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder

X_categorical = OneHotEncoder().fit_transform(df_filtered['issueArea'].values.reshape(-1, 1)).toarray()
X_train, X_test, y_train, y_test = train_test_split(X_categorical, y, test_size=0.3, random_state=42)

mlp = MLPClassifier(random_state=42)

# Train the classifier on the input data
mlp.fit(X_train, y_train)

# Get predictions on the test data
y_pred = mlp.predict(X_test)

# Compute the confusion matrix and accuracy
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

# Print the confusion matrix and accuracy
print(cm)
print(accuracy)

[[4999 6019]
 [3927 8253]]
0.5712561427709285


In [ ]:
actual_vote = df_caseId['direction']
actual_vote

Averages of Current Supreme Court Members

In [ ]:
judges = ['JGRoberts', 'CThomas','SGBreyer', 'SAAlito', 'SSotomayor', 'EKagan', 'NMGorsuch', 'BMKavanaugh', 'ACBarrett']

score_list = []

for i in range(len(judges)):
  df_ingeneral = df[(df['justiceName'] == judges[i])]
  df_ingeneral = df_ingeneral[df_ingeneral['decisionDirection'] > 0]
  total_sum = sum(df_ingeneral['decisionDirection'])
  score = total_sum / len(df_ingeneral['decisionDirection'])
  print(judges[i])
  print(score)
  score_list.append(score)

score_3 = sum(score_list) /  len(score_list)
print(f"Average Score: {score_3}")

In [ ]:
import random
print(f"Random Score: {1+random.random()}")
print(f"Average Score: {score_3}")
# random.choice(judges)

Random Score: 1.230069910512808
Average Score: 1.51446686153063


STOP HERE

In [ ]:
df['caseId'].unique()

array(['1946-001', '1946-002', '1946-003', ..., '2021-067', '2021-068',
       '2021-069'], dtype=object)

In [ ]:
df_ingeneral['decisionDirection']

80853    3.0
80862    1.0
80871    2.0
80880    2.0
80889    2.0
        ... 
81978    2.0
81987    1.0
81996    1.0
82005    1.0
82014    2.0
Name: decisionDirection, Length: 128, dtype: float64